(*
    Copyright (c) 2000
        Cambridge University Technical Services Limited

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.
    
    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.
    
    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*)

functor ML32Fct ( (*structure ConstType : ConstTypeSig
                      structure Type : TypeSig
                      structure UserFn : UserFnSig
                      structure UserFn2 : UserFn2Sig
                      structure GdiFn : GdiFnSig
                      structure CtrlFn : CtrlFnSig
                      structure Gadget : GadgetSig *) 
                ) =
struct
open ConstType
open MsgFn
open Type32
open UserFn
open UserFn2
open GdiFn
open CtrlFn
open Gadget
open Failure

structure DrawCommands = DrawCom
structure Advanced = struct  end
end
