.TH POLY 1 "Poly/ML Version 5.1 2007"
.SH NAME
poly \- the Poly/ML Standard ML implementation
.SH SYNOPSIS
.B poly
.SH DESCRIPTION
.I poly
starts the Poly/ML shell. Poly/ML is an implementation of Standard ML developed by David Matthews at
Cambridge and at the Laboratory for Foundations of Computer Science (LFCS) at Edinburgh. 
.SH OPTIONS
.TP
.B \-v
Print the version of Poly/ML and exit.
.TP
.B \--help
Print a list of the arguments and exit.
.TP
.B \-q
Suppress the start-up message.
.TP
.BI \-H " size"
Set the initial heap size, in MB.
.TP
.BI \--heap " size"
Set the initial heap size, in MB.
.TP
.BI \--immutable " size"
Set the size of the immutables buffer, in MB.
.TP
.BI \--mutable " size"
Set the size of the mutables buffer, in MB.
.TP
.BI \--timeslice " timeslice
Set the timeslice.
.TP
.BI \--debug " level"
Set the debugging level.
.fi
.SH SEE ALSO
.PP
.B http://www.poly.org
The Poly/ML web site.
